version: '3.9'

# container networking
networks:
  cicd-network: 
    name: cicd-network

services:
  jenkins:
      image: jenkins/jenkins:2.335-jdk11
      networks: 
        - cicd-network
      privileged: true
      user: root
      restart: unless-stopped
      ports:
        - target: 8080
          published: 8083
          protocol: tcp
          mode: host
      container_name: jenkins
      # volumes:
      #   # - /Users/admin/docker-data/jenkins:/var/jenkins_home
      #   - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - JAVA_OPTS=-Xms512m -Xmx2g -Djava.awt.headless=true


  sonarqube:
      image: sonarqube:8-community
      networks: 
        - cicd-network
      container_name: sonarqube
      # depends_on:
      #   - sonarqube-db
      # links:
      #   - sonarqube-db
      # environment:
      #   SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      #   SONAR_JDBC_USERNAME: sonar
      #   SONAR_JDBC_PASSWORD: sonar
      # volumes:
      #   - /Users/admin/docker-data/sonarqube/data:/opt/sonarqube/data
      #   - /Users/admin/docker-data/sonarqube/extensions:/opt/sonarqube/extensions
      #   - /Users/admin/docker-data/sonarqube/logs:/opt/sonarqube/logs
      #   - /Users/admin/docker-data/sonarqube/temp:/opt/sonarqube/temp
      ports:
        - target: 9000
          published: 8084
          protocol: tcp
          mode: host
      restart: always

  # sonarqube-db:
  #   image: postgres:12
  #   container_name: sonarqube-db
  #   networks: 
  #     - cicd-network
  #   environment:
  #     POSTGRES_PASSWORD: sonar
  #     SONARQUBE_DB_USER: sonar
  #     SONARQUBE_DB_PASSWORD: sonar
  #     SONARQUBE_DB: sonar
  #   volumes:
  #     - /Users/admin/docker-data/sonarqube/db-data:/var/lib/postgresql

  # artifactory-db:
  #   image: postgres:12
  #   container_name: artifactory-db
  #   networks: 
  #     - cicd-network
  #   environment:
  #     POSTGRES_PASSWORD: artifactory
  #     ARTIFACTORY_DB_USER: artifactory
  #     ARTIFACTORY_DB_PASSWORD: artifactory
  #     ARTIFACTORY_DB: artifactory
    # volumes:
    #   - /Users/admin/docker-data/artifactory/db-data:/var/lib/postgresql

  # Artifactory service
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
    container_name: artifactory
    networks: 
      - cicd-network
    ports:
    - target: 8081
      published: 8085
      protocol: tcp
      mode: host
    # volumes:
    #  - /Users/admin/docker-data/artifactory:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000






