{{- /*
library-route.util.merge will merge two YAML templates and output the result.
This takes an array of three values:
- the top context
- the template name of the overrides (destination)
- the template name of the base (source)
*/ -}}
{{- define "library-route.util.merge" -}}
{{- $top := first . -}}
{{- $overrides := fromYaml (include (index . 1) $top) | default (dict ) -}}
{{- $tpl := fromYaml (include (index . 2) $top) | default (dict ) -}}
{{- toYaml (merge $overrides $tpl) -}}
{{- end -}}

{{- define "library-route.util.resolve" -}}
  {{- with .context }}
    {{- $releaseName := .Release.Name -}}
    {{- if hasKey (get .Values $releaseName | default (dict)) $.key }}
      {{- get (get .Values $releaseName ) $.key -}}
    {{- else if hasKey (get .Values "route" | default (dict)) $.key }}
      {{- (get .Values.route $.key ) -}}
    {{- else}}
      {{- (get .Values $.key ) -}}
    {{- end }}
  {{- end }}
{{- end -}}
