apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv
  namespace: sonarqube
spec:
  storageClassName: vsphere-csi-sc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/sonarqube-volume/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-sonarqube
  namespace: sonarqube
spec:
  storageClassName: vsphere-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: "sonarqube-pv"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: data-sonarqube-postgresql
#   namespace: sonarqube
# spec:
#   storageClassName: vsphere-csi-sc
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 30Gi
#   volumeName: "sonarqube-pv"