{{- define "library-nginx.dc.tpl" -}}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Release.Name }}
    repo: broker-helm-charts
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ include "library-nginx.util.resolve" (dict "key" "minReplicas" "context" $) | default 2 }}
  selector:
    app: {{ .Release.Name }}
    deploymentconfig: {{ .Release.Name }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        deploymentconfig: {{ .Release.Name }}
        repo: broker-helm-charts
    spec:
      containers:
      - env:
        - name: OIDC_HOST
          value: {{ include "library-nginx.util.resolve" (dict "key" "oidcHost" "context" $) }}
        - name: OIDC_CLIENT
          value: {{ include "library-nginx.util.resolve" (dict "key" "oidcClient" "context" $) }}
        - name: OIDC_CLIENT_SECRET
          value: {{ include "library-nginx.util.resolve" (dict "key" "oidcClientSecret" "context" $) }}
        - name: OIDC_HMAC_KEY
          value: {{ include "library-nginx.util.resolve" (dict "key" "oidcHmacKey" "context" $) }}
        image: {{ .Values.registryHost }}/{{ .Values.registryOrg }}/{{ .Release.Name }}:{{ include "library-nginx.util.resolve" (dict "key" "imageVersion" "context" $) | default "latest" }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: {{ include "library-nginx.util.resolve" (dict "key" "probeInitialDelaySeconds" "context" $) | default 20 }}
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: {{ include "library-nginx.util.resolve" (dict "key" "probeTimeoutSeconds" "context" $) | default 5 }}
        name: {{ .Release.Name }}
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: {{ include "library-nginx.util.resolve" (dict "key" "probeInitialDelaySeconds" "context" $) | default 20 }}
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: {{ include "library-nginx.util.resolve" (dict "key" "probeTimeoutSeconds" "context" $) | default 5 }}
        resources:
          limits:
            cpu: {{ include "library-nginx.util.resolve" (dict "key" "resourceLimitsCpu" "context" $) | default "250m" | quote }}
            memory: {{ include "library-nginx.util.resolve" (dict "key" "resourceLimitsMemory" "context" $) | default "768Mi" | quote }}
          requests:
            cpu: {{ include "library-nginx.util.resolve" (dict "key" "resourceRequestsCpu" "context" $) | default "100m" | quote }}
            memory: {{ include "library-nginx.util.resolve" (dict "key" "resourceRequestsMemory" "context" $) | default "512Mi" | quote }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: volume-cert
          readOnly: true
        - mountPath: /etc/nginx/conf.d
          name: volume-nginx-config
        - mountPath: /var/log/nginx
          name: nginx-logs
      - env:
        - name: APPLICATION_NAME
          value: {{ .Release.Name }}
        - name: DATA_CENTER
          value: {{ .Values.dataCenter }}
        - name: REGION
          value: {{ .Values.region }}
        - name: ENVIRONMENT
          value: {{ .Values.environment }}
        image: {{ .Values.registryHost }}/{{ .Values.registryOrg }}/broker-rsyslog-client:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - rsyslogd
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: {{ .Release.Name }}-logging-sidecar
        readinessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - rsyslogd
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ include "library-nginx.util.resolve" (dict "key" "syslogClientResourceLimitsCpu" "context" $) | default "10m" | quote }}
            memory: {{ include "library-nginx.util.resolve" (dict "key" "syslogClientResourceLimitsMemory" "context" $) | default "32Mi" | quote }}
          requests:
            cpu: {{ include "library-nginx.util.resolve" (dict "key" "syslogClientResourceRequestsCpu" "context" $) | default "5m" | quote }}
            memory: {{ include "library-nginx.util.resolve" (dict "key" "syslogClientResourceRequestsMemory" "context" $) | default "16Mi" | quote }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/var/log/nginx
          name: nginx-logs
        - mountPath: /app/config
          name: volume-rsyslog-config
      dnsConfig:
        searches:
        - wellpoint.com
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretName }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: nginx-logs
      - configMap:
          defaultMode: 420
          name: rsyslog-client
        name: volume-rsyslog-config
      - configMap:
          defaultMode: 420
          items:
          - key: frontend.conf
            path: frontend.conf
          - key: openid_connect.js
            path: extras/openid_connect.js
          - key: openid_connect_server.conf
            path: extras/openid_connect_server.conf
          - key: zipkin-config.json
            path: extras/zipkin-config.json
          - key: oidc_config.conf
            path: extras/oidc_config.conf
          - key: openid_auth.conf
            path: extras/openid_auth.conf
          name: nginx
        name: volume-nginx-config
      - name: volume-cert
        secret:
          defaultMode: 420
          secretName: bp-nginx-certs
  triggers:
  - type: ConfigChange
{{- end -}}
{{- define "library-nginx.dc" -}}
{{- include "library-nginx.util.merge" (append . "library-nginx.dc.tpl") -}}
{{- end -}}
