environments:
  default:
  dev:
  qa:
  uat:
  prod:
  dr:
  blue:

helmDefaults:
  recreatePods: true
  historyMax: 10
  tillerless: true
  wait: true
  timeout: 600
  # createNamespace: false

templates:
  default: &default
    namespace: broker-portal-{{`{{ .Environment.Name }}`}}ocp
    labels:
      channel: broker-mobile
    missingFileHandler: Warn
    values:
    - ../../config/default.yaml
    - ../../config/environment/{{ .Environment.Name }}.yaml

releases:

- name: broker-notification-service
  chart: ../../charts/base/nodejs
  <<: *default

- name: graphql-applications-service
  chart: ../../charts/base/graphql
  <<: *default

- name: graphql-commissions-service
  chart: ../../charts/base/graphql
  <<: *default

- name: graphql-content-service
  chart: ../../charts/base/graphql
  <<: *default

- name: graphql-quotes-service
  chart: ../../charts/base/graphql
  <<: *default

- name: graphql-userprofile-service
  chart: ../../charts/base/graphql
  <<: *default

- name: opportunity-service
  chart: ../../charts/base/java
  <<: *default

- name: producer-tools-auth-service
  chart: ../../charts/base/nodejs
  <<: *default
