kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ad-eks-dev
  namespace: default
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: eks-sso-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ad-eks-dev
