# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sso-dev-admin-clusterrole-bindings
subjects:
- kind: Group
  name: sso-dev-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sso-dev-admin-clusterrole
  apiGroup: rbac.authorization.k8s.io