kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: ad-eks-dev
rules:
  - verbs:
      - get
      - list
      - watch
      - create
    apiGroups:
      - ''
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
      - pods
