fullnameOverride: ingress-nginx

controller:
  name: controller
  enableAnnotationValidations: false
  image:
    chroot: false
    registry: registry.k8s.io
    image: ingress-nginx/controller
    tag: "v1.10.0"
    containerName: ingress-nginx-controller
    pullPolicy: IfNotPresent
    runAsNonRoot: true
    runAsUser: 101
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    readOnlyRootFilesystem: false
    service:
      enabled: true
      external:
        enabled: true
      annotations: {}
      type: NodePort
  extraArgs:
    enable-ssl-passthrough: true

