apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: sample-eksa1
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "10.0.0.254"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: sample-eksa1-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: sample-eksa1
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: sample-eksa1-etcd
  kubernetesVersion: "1.21"
  workerNodeGroupConfigurations:
  - count: 5
    machineGroupRef:
      kind: VSphereMachineConfig
      name: sample-eksa1

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: sample-eksa1
spec:
  datacenter: "dc-east"
  insecure: true
  network: "vmPub"
  server: "10.0.0.31"
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: sample-eksa1-cp
spec:
  datastore: "WorkloadDatastore (2)"
  diskGiB: 25
  # folder: "/SDDC-Datacenter/vm/Linux-Lab"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  # resourcePool: "Compute-ResourcePool-3"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: sample-eksa1
spec:
  datastore: "vmData"
  diskGiB: 25
  # folder: "/SDDC-Datacenter/vm/Linux-Lab"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  # resourcePool: "Compute-ResourcePool-3"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: sample-eksa1-etcd
spec:
  datastore: "vmData"
  diskGiB: 25
  # folder: "/SDDC-Datacenter/vm/Linux-Lab"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  # resourcePool: "Compute-ResourcePool-3"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""
---
arn:aws:iam::202334955716:role/AWSReservedSSO_Guest_Exp_DevOps_449f6a554cd8830c
- groups:
      - system:masters
      rolearn: arn:aws:iam::202334955716:role/AWSReservedSSO_Guest_Exp_DevOps_449f6a554cd8830c
      username: slalom-admin:{{SessionName}}

