apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: sandbox-eksa
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "10.0.0.253"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: sandbox-eksa-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: sandbox-eksa
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: sandbox-eksa-etcd
  kubernetesVersion: "1.21"
  workerNodeGroupConfigurations:
  - count: 5
    machineGroupRef:
      kind: VSphereMachineConfig
      name: sandbox-eksa

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: sandbox-eksa
spec:
  datacenter: "dc-east"
  insecure: true
  network: "vmPublic"
  server: "10.0.0.31"
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: sandbox-eksa-cp
spec:
  datastore: "vmData"
  diskGiB: 100
  folder: "eksa"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "Resources"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: sandbox-eksa
spec:
  datastore: "vmData"
  diskGiB: 100
  folder: "eksa"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "Resources"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: sandbox-eksa-etcd
spec:
  datastore: "vmData"
  diskGiB: 100
  folder: "eksa"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "Resources"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""
---

