version: '3.8'
services:
  jenkins:
      image: jenkins/jenkins:2.277.4-lts
      networks: 
        - cicd-network
      mem_limit: 1000m
      mem_reservation: 128M
      cpus: 0.5
      privileged: true
      user: root
      restart: unless-stopped
      ports:
        - target: 8080
          published: 8080
          protocol: tcp
          mode: host
      container_name: jenkins
      volumes:
        - /Users/admin/docker-data/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - JAVA_OPTS=-Xms512m -Xmx2g -Djava.awt.headless=true

networks:
  cicd-network: 
    name: cicd-network
