# sample-playbook.yml
---
- name: Create VM folder on vsphere datacenter
  hosts: localhost
  gather_facts: true
  become: yes

  vars_files:
    - ./sample-vars.yml

  tasks:
    - name: Create VM folder on vsphere datacenter
      import_tasks: ./create-vm-folder.yml 
