apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsphere-csi-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  datastoreurl: "ds:///vmfs/volumes/vmData/"
  csi.storage.k8s.io/fstype: "ext4"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
