# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

## Overrides for generated resource names
# See templates/_helpers.tpl
# -- Override the resource name prefix
# @default -- `Chart.Name`
nameOverride:
# -- Override the full resource names
# @default -- `jenkins-(release-name)` or `jenkins` if the release-name is `jenkins`
fullnameOverride:
# -- Override the deployment namespace
# @default -- `Release.Namespace`
namespaceOverride:

# For FQDN resolving of the controller service. Change this value to match your existing configuration.
# ref: https://github.com/kubernetes/dns/blob/master/docs/specification.md
# -- Override the cluster name for FQDN resolving
clusterZone: "tools-k8s-cluster"

# -- The URL of the Kubernetes API server
kubernetesURL: "https://tools-k8s-cluster-api.labz.io:6443"

# -- The Jenkins credentials to access the Kubernetes API server. For the default cluster it is not needed.
credentialsId:

# -- Enables rendering of the helm.sh/chart label to the annotations
renderHelmLabels: true

controller:
  componentName: "jenkins-controller"
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "2.456"
    pullPolicy: "Always"
  imagePullSecretName:
  disableRememberMe: true
  numExecutors: 1
  executorMode: "NORMAL"
  jenkinsHome: "/var/jenkins_home"
  serviceType: ClusterIP
  servicePort: 80
  targetPort: 8080
  cloudName: "kubernetes"
  installPlugins:
    - kubernetes:4209.vc646b_71e5269
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.2.1
    - configuration-as-code:1775.v810dc950b_514
  installLatestPlugins: true
  installLatestSpecifiedPlugins: false
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  podSecurityContextOverride:
    runAsUser: 0
    supplementalGroups: [0]
    fsGroup: 0
  ingress:
    enabled: false
    paths: 
    - backend:
        serviceName: >-
          {{ template "jenkins.fullname" . }}
        servicePort: 8080
      pathType: Prefix
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations: {}
    hostName: "jenkins.labz.io"
    resourceRootUrl:
    tls: []

agent:
  enabled: true
  defaultsProviderTemplate: ""
  kubernetesConnectTimeout: 5
  kubernetesReadTimeout: 15
  maxRequestsPerHostStr: "32"
  retentionTimeout: 5
  waitForPodSec: 600
  image:
    repository: "jenkins/inbound-agent"
    tag: "3206.vb_15dcf73f6a_9-3"
  workingDir: "/home/jenkins/agent"
  nodeUsageMode: "NORMAL"
  customJenkinsLabels: []
  imagePullSecretName:
  componentName: "jenkins-agent"
  websocket: false
  directConnection: false
  privileged: true
  hostNetworking: false
  yamlTemplate: ""

  yamlMergeStrategy: "override"
  connectTimeout: 100
  annotations: {}

  additionalContainers: []

  disableDefaultAgent: false

  podTemplates: {}
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

persistence:
  enabled: true
  existingClaim: "jenkins-pvc"

