image:
  repository: registry.k8s.io/metrics-server/metrics-server
  tag: ""
  pullPolicy: IfNotPresent

fullnameOverride: "metrics-server"

serviceAccount:
  create: true
  annotations: {}
  name: "metrics-server-sa"
  secrets: []

rbac:
  create: true
  pspEnabled: false

apiService:
  create: true
  annotations: {}
  insecureSkipTLSVerify: true

replicas: 1


defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --kubelet-insecure-tls
  - --metric-resolution=15s


service:
  type: ClusterIP
  port: 443
  annotations: {}
  labels: {}


metrics:
  enabled: true

serviceMonitor:
  enabled: false
  additionalLabels: {}
  interval: 1m
  scrapeTimeout: 10s
  metricRelabelings: []
  relabelings: []

