apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  namespace: demo-operator
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/